//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeCycleWorkflowLibrary.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputLocationTheBayWip {
            get {
                return ((string)(this["OutputLocationTheBayWip"]));
            }
            set {
                this["OutputLocationTheBayWip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputLocationTheBayFinal {
            get {
                return ((string)(this["OutputLocationTheBayFinal"]));
            }
            set {
                this["OutputLocationTheBayFinal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultOutputLocation {
            get {
                return ((string)(this["DefaultOutputLocation"]));
            }
            set {
                this["DefaultOutputLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TheBayManualDataLoadInventoryAmountFile {
            get {
                return ((string)(this["TheBayManualDataLoadInventoryAmountFile"]));
            }
            set {
                this["TheBayManualDataLoadInventoryAmountFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TheBayManualDataLoadNosFile {
            get {
                return ((string)(this["TheBayManualDataLoadNosFile"]));
            }
            set {
                this["TheBayManualDataLoadNosFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TheBayManualDataLoadNosCombinedFile {
            get {
                return ((string)(this["TheBayManualDataLoadNosCombinedFile"]));
            }
            set {
                this["TheBayManualDataLoadNosCombinedFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TheBayManualDataLoadInactiveUpcFile {
            get {
                return ((string)(this["TheBayManualDataLoadInactiveUpcFile"]));
            }
            set {
                this["TheBayManualDataLoadInactiveUpcFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TemplatePathTheBayWip {
            get {
                return ((string)(this["TemplatePathTheBayWip"]));
            }
            set {
                this["TemplatePathTheBayWip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TemplatePathTheBayFinal {
            get {
                return ((string)(this["TemplatePathTheBayFinal"]));
            }
            set {
                this["TemplatePathTheBayFinal"] = value;
            }
        }
    }
}
